[tool.ruff]
line-length = 83

[tool.ruff.format]
quote-style = "single"
indent-style = "space"

[tool.pytest.ini_options]
asyncio_mode = "strict"
pythonpath = "."
markers = [
    "asyncio: mark test as async",
]